<?php

namespace AppBundle\Repository;

/**
 * BasePizzaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasePizzaRepository extends \Doctrine\ORM\EntityRepository
{
}
