<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends EntityRepository {

    public function findCommandNotDone() {
//        $em = $this->getDoctrine()->getManager();
        $query = $this->getEntityManager()->createQuery(
                        'SELECT c
                        FROM AppBundle:Commande c
                        WHERE c.statut < :statut
                        ORDER BY c.heure ASC'
                )->setParameter('statut', 3);
        return $query->getResult();
    }

}
