<?php

namespace AppBundle\Repository;

/**
 * EnseigneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnseigneRepository extends \Doctrine\ORM\EntityRepository
{
}
