<?php

namespace AppBundle\Repository;

/**
 * ModePaiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModePaiementRepository extends \Doctrine\ORM\EntityRepository
{
}
