<?php

namespace AppBundle\Repository;

/**
 * PizzaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PizzaRepository extends \Doctrine\ORM\EntityRepository
{
}
