<?php

namespace AppBundle\Repository;

/**
 * TailleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TailleRepository extends \Doctrine\ORM\EntityRepository
{
}
